port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
proxies:
  - name: HZ ID 02
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 649cc7d3-1846-4eec-8796-35d09f97bc22
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id04.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id04.gproxy.pro
    udp: true
  - name: TROJAN CH SG 01
    server: 172.67.5.14
    port: 443
    type: trojan
    password: ed3b277e-6d16-4050-bfc2-9cb4b1b30e0e
    skip-cert-verify: true
    sni: tro-sg02.gproxy.pro
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: tro-sg02.gproxy.pro
    udp: true
  - name: Tro MBC SG 03
    server: 172.67.5.14
    port: 443
    type: trojan
    password: 719b07db-1f4c-4218-8c5a-8e991042099f
    skip-cert-verify: true
    sni: tro-sg03.gproxy.pro
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: tro-sg03.gproxy.pro
    udp: true
  - name: TROJAN GS SG 01
    server: 172.67.5.14
    port: 443
    type: trojan
    password: 129af750-09f1-40bb-9a64-d5df74038ace
    skip-cert-verify: true
    sni: tro-sg04.gproxy.pro
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: tro-sg04.gproxy.pro
    udp: true
  - name: AMP ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 1e38b50f-910d-4c7f-aaf0-55f3e47aa761
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id01.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id01.gproxy.pro
    udp: true
  - name: BN ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 60792418-cacb-4cad-9c65-009ffd504104
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id06.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id06.gproxy.pro
    udp: true
  - name: CTN ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: b6f24b53-e8ff-4395-abf6-98d2ec280792
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id05.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id05.gproxy.pro
    udp: true
  - name: NNS ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: b49e2f38-f3ab-4c81-b807-9ff02ba9a372
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id07.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id07.gproxy.pro
    udp: true
  - name: NNS ID 02
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 430e7896-f3f8-4e84-b563-f27dfd767c7f
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id08.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id08.gproxy.pro
    udp: true
  - name: RCH ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: c60068e2-6278-46e2-8435-50cd4a985c50
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id05.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id05.gproxy.pro
    udp: true
  - name: RM ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 01d9e94c-885f-43a1-a0b1-aa05c42bc35d
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id07.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id07.gproxy.pro
    udp: true
  - name: IDK-1
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 0297a588-40b3-4557-ba88-9317a2d949cb
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: to.idk1.workers.dev
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: to.idk1.workers.dev
    udp: true
  - name: UMS ID 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: d78bd4da-3168-4833-888e-57373b06fd5c
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-id11.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-id11.gproxy.pro
    udp: true
  - name: GS SG 01
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: d902b035-c2e0-4cec-b3a7-8302f2495cca
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-sg04.gproxy.pro
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-sg04.gproxy.pro
    udp: true
  - name: ID3 Tifa
    server: 172.67.5.14
    port: 443
    type: vmess
    uuid: 9a4c415e-252b-4d09-b42e-d87e719b8c31
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id3.servercepat.net
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: id3.servercepat.net
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - HZ ID 02
      - TROJAN CH SG 01
      - Tro MBC SG 03
      - TROJAN GS SG 01
      - AMP ID 01
      - BN ID 01      
      - CTN ID 01    
      - NNS ID 01     
      - NNS ID 02      
      - RCH ID 01   
      - RM ID 01     
      - IDK-1  
      - UMS ID 01  
      - GS SG 01  
      - ID3 Tifa                                  
      - DIRECT
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY